// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3-S6ue20UhrQQqal844wgBi5to6VDPLk',
    appId: '1:698433269188:web:2e4e1eee8544e397164891',
    messagingSenderId: '698433269188',
    projectId: 'chat-app-1dbb6',
    authDomain: 'chat-app-1dbb6.firebaseapp.com',
    storageBucket: 'chat-app-1dbb6.appspot.com',
    measurementId: 'G-1G9FKHDH2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCELdsh48a3U0Tkv7M4Eaeh62OR_RIHzQ',
    appId: '1:698433269188:android:5c9520bff9b44672164891',
    messagingSenderId: '698433269188',
    projectId: 'chat-app-1dbb6',
    storageBucket: 'chat-app-1dbb6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD_-ALvw475YJZ8B2lN2MgB8JkAuvdQdM',
    appId: '1:698433269188:ios:3ab52548fec70163164891',
    messagingSenderId: '698433269188',
    projectId: 'chat-app-1dbb6',
    storageBucket: 'chat-app-1dbb6.appspot.com',
    iosClientId: '698433269188-qpt8nt343bdr2ncu2o42j68jh9up7onc.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
